name: Download file
on:
  push:

jobs:
  download-crds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download CRDs
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'cert-manager/cert-manager'
          #version: 'tags/v0.1.18'  # Uncomment and modify as needed
          file: "cert-manager.crds.yaml"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: adding latest CRDs"
