name: Download file
on:
  push:

jobs:
  download-crds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download CRDs
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'cert-manager/cert-manager'
          #version: 'tags/v0.1.18'  # Uncomment and modify as needed
          file: "cert-manager.crds.yaml"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Git Status
        run: ls -al
