name: Download file
on:
  push:


jobs:
  download-crds:
    uses: dsaltares/fetch-gh-release-asset@master
    with:
      repo: 'https://github.com/cert-manager/cert-manager'
      #version: 'tags/v0.1.18'
      regex: true
      file: ".*crds\\.yaml"
      token: ${{ secrets.GITHUB_TOKEN }}
